services:
  postgres:
    image: postgres:15
    container_name: sql_producer_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sql-producer-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: sql_producer_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - sql-producer-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongodb:
    image: mongo:latest
    container_name: sql_producer_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    restart: unless-stopped
    networks:
      - sql-producer-network

networks:
  sql-producer-network:
    name: sql-producer-network
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  pgadmin-data:
