services:
  postgres:
    image: postgres:15
    container_name: sql_producer_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-sqlproducer}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: sql_producer_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ./postgres/pgadmin/servers.json:/pgadmin4/servers.json

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
