apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: sql-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-producer-secrets
                  key: pgadmin-password
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: sql-producer
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
